import SimpleSidebar from "@/components/sidebar/page";
import { Box } from "@chakra-ui/react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Providers } from "./providers";
import { ReduxProvider } from "@/redux/provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>
          <SimpleSidebar />
          <Box ml="10vw" mr="200px">
            <Providers>{children}</Providers>
          </Box>
        </ReduxProvider>
      </body>
    </html>
  );
}
